/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

module.exports = {
   content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
   safelist: [
      //titlebar
      "bg-destructive-default",
      "bg-accent-primary",
      "hover:bg-red-500",
      "hover:bg-base-40",
      "text-sm",
      "text-md",
      "text-lg",
   ],
   theme: {
      colors: {
         // base: {
         //    0o0: "var(--base-00)",
         //    0o5: "var(--base-05)",
         //    10: "var(--base-10)",
         //    15: "var(--base-15)",
         //    20: "var(--base-20)",
         //    25: "var(--base-25)",
         //    30: "var(--base-30)",
         //    35: "var(--base-35)",
         //    40: "var(--base-40)",
         //    50: "var(--base-50)",
         //    60: "var(--base-60)",
         //    70: "var(--base-70)",
         //    80: "var(--base-80)",
         //    90: "var(--base-90)",
         //    100: "var(--base-100)",
         //    110: "var(--base-110)",
         //    120: "var(--base-120)",
         // },
         // brand: {
         //    1000: "var(--brand-1000)",
         //    900: "var(--brand-900)",
         //    800: "var(--brand-800)",
         //    700: "var(--brand-700)",
         //    600: "var(--brand-600)",
         //    500: "var(--brand-500)",
         //    400: "var(--brand-400)",
         //    300: "var(--brand-300)",
         //    200: "var(--brand-200)",
         //    100: "var(--brand-100)",
         // },
         // warning: {
         //    1000: "var(--warning-1000)",
         //    900: "var(--warning-900)",
         //    800: "var(--warning-800)",
         //    700: "var(--warning-700)",
         //    600: "var(--warning-600)",
         //    500: "var(--warning-500)",
         //    400: "var(--warning-400)",
         //    300: "var(--warning-300)",
         //    200: "var(--warning-200)",
         //    100: "var(--warning-100)",
         // },
         // destructive: {
         //    1000: "var(--destructive-1000)",
         //    900: "var(--destructive-900)",
         //    800: "var(--destructive-800)",
         //    700: "var(--destructive-700)",
         //    600: "var(--destructive-600)",
         //    500: "var(--destructive-500)",
         //    400: "var(--destructive-400)",
         //    300: "var(--destructive-300)",
         //    200: "var(--destructive-200)",
         //    100: "var(--destructive-100)",
         // },
         // success: {
         //    1000: "var(--success-1000)",
         //    900: "var(--success-900)",
         //    800: "var(--success-800)",
         //    700: "var(--success-700)",
         //    600: "var(--success-600)",
         //    500: "var(--success-500)",
         //    400: "var(--success-400)",
         //    300: "var(--success-300)",
         //    200: "var(--success-200)",
         //    100: "var(--success-100)",
         // },
         // background: {
         //    // darkmode
         //    "primary-dark": "var(--background-primary-dark)",
         //    "primary-alt-dark": "var(--background-primary-alt-dark)",
         //    "secondary-dark": "var(--background-secondary-dark)",
         //    "secondary-alt-dark": "var(--background-secondary-alt-dark)",
         //    "tertiary-dark": "var(--background-tertiary-dark)",
         //    "tertiary-alt-dark": "var(--background-tertiary-alt-dark)",
         //    "overlay-dark": "var(--background-overlay-dark)",
         //    "hover-dark": "var(--background-hover-dark)",
         //    "focus-dark": "var(--background-focus-dark)",
         //    "accent-dark": "var(--background-accent-dark)",
         //    "muted-dark": "var(--background-muted-dark)",
         //    "darker-dark": "var(--background-darker-dark)",
         //    "alt-dark": "var(--background-alt-dark)",
         //    "light-dark": "var(--background-light-dark)",
         //    "border-dark": "var(--background-border-dark)",
         //    // lightmode
         //    "primary-light": "var(--background-primary-light)",
         //    "primary-alt-light": "var(--background-primary-alt-light)",
         //    "secondary-light": "var(--background-secondary-light)",
         //    "secondary-alt-light": "var(--background-secondary-alt-light)",
         //    "tertiary-light": "var(--background-tertiary-light)",
         //    "tertiary-alt-light": "var(--background-tertiary-alt-light)",
         //    "overlay-light": "var(--background-overlay-light)",
         //    "hover-light": "var(--background-hover-light)",
         //    "focus-light": "var(--background-focus-light)",
         //    "accent-light": "var(--background-accent-light)",
         //    "muted-light": "var(--background-muted-light)",
         //    "lighter-light": "var(--background-lighter-light)",
         //    "alt-light": "var(--background-alt-light)",
         //    "lightest-light": "var(--background-lightest-light)",
         //    "border-light": "var(--background-border-light)",
         //    // mixed
         //    warning: "var(--background-warning)",
         //    "warning-light": "var(--background-warning-light)",
         //    destructive: "var(--background-destructive)",
         //    "destructive-light": "var(--background-destructive-light)",
         //    "brand-primary": "var(--background-brand-primary)",
         //    "brand-primary-alt": "var(--background-brand-primary-alt)",
         //    "brand-secondary": "var(--background-brand-secondary)",
         //    "brand-secondary-alt": "var(--background-brand-secondary-alt)",
         //    "brand-accent": "var(--background-brand-accent)",
         // },
         // border: {
         //    // darkmode
         //    "primary-dark": "var(--border-primary-dark)",
         //    "secondary-dark": "var(--border-secondary-dark)",
         //    "tertiary-dark": "var(--border-tertiary-dark)",
         //    "primary-alt-dark": "var(--border-primary-alt-dark)",
         //    "secondary-alt-dark": "var(--border-secondary-alt-dark)",
         //    "tertiary-alt-dark": "var(--border-tertiary-alt-dark)",
         //    "muted-dark": "var(--border-muted-dark)",
         //    // lightmode
         //    "primary-light": "var(--border-primary-light)",
         //    "secondary-light": "var(--border-secondary-light)",
         //    "tertiary-light": "var(--border-tertiary-light)",
         //    "primary-alt-light": "var(--border-primary-alt-light)",
         //    "secondary-alt-light": "var(--border-secondary-alt-light)",
         //    "tertiary-alt-light": "var(--border-tertiary-alt-light)",
         //    "muted-light": "var(--border-muted-light)",
         // },
         // text: {
         //    // darkmode
         //    "normal-dark": "var(--text-normal-dark)",
         //    "muted-dark": "var(--text-muted-dark)",
         //    "faint-dark": "var(--text-faint-dark)",
         //    "on-accent-dark": "var(--text-on-accent-dark)",
         //    "on-accent-inverted-dark": "var(--text-on-accent-inverted-dark)",
         //    "error-dark": "var(--text-error-dark)",
         //    "warning-dark": "var(--text-warning-dark)",
         //    "info-dark": "var(--text-info-dark)",
         //    "link-dark": "var(--text-link-dark)",
         //    "heading-dark": "var(--text-heading-dark)",
         //    "placeholder-dark": "var(--text-placeholder-dark)",
         //    "disabled-dark": "var(--text-disabled-dark)",
         //    "brand-accent-dark": "var(--text-brand-accent-dark)",
         //    // lightmode
         //    "normal-light": "var(--text-normal-light)",
         //    "muted-light": "var(--text-muted-light)",
         //    "faint-light": "var(--text-faint-light)",
         //    "on-accent-light": "var(--text-on-accent-light)",
         //    "on-accent-inverted-light": "var(--text-on-accent-inverted-light)",
         //    "error-light": "var(--text-error-light)",
         //    "warning-light": "var(--text-warning-light)",
         //    "info-light": "var(--text-info-light)",
         //    "link-light": "var(--text-link-light)",
         //    "heading-light": "var(--text-heading-light)",
         //    "placeholder-light": "var(--text-placeholder-light)",
         //    "disabled-light": "var(--text-disabled-light)",
         //    "brand-accent-light": "var(--text-brand-accent-light)",
         // },
      },
      // boxShadow: {
      //    "input-shadow":
      //       "inset 0 0.5px 0.5px 0.5px rgba(255, 255, 255, 0.09), 0 2px 4px 0 rgba(0, 0, 0, .15), 0 1px 1.5px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .2), 0 0 0 0 transparent",
      //    "input-shadow-hover":
      //       "inset 0 0.5px 1px 0.5px rgba(255, 255, 255, 0.16), 0 2px 3px 0 rgba(0, 0, 0, .3), 0 1px 1.5px 0 rgba(0, 0, 0, .2), 0 1px 2px 0 rgba(0, 0, 0, .4), 0 0 0 0 transparent",
      //    "shadow-s":
      //       "0px 1px 2px rgba(0, 0, 0, 0.121), 0px 3.4px 6.7px rgba(0, 0, 0, 0.179), 0px 15px 30px rgba(0, 0, 0, 0.3)",
      //    "shadow-l":
      //       "0px 1.8px 7.3px rgba(0, 0, 0, 0.071), 0px 6.3px 24.7px rgba(0, 0, 0, 0.112), 0px 30px 90px rgba(0, 0, 0, 0.2)",
      // },

      fontSize: {
         "fs-default": "var(--default)",
         "fs-xs": "var(--xs)",
         "fs-sm": "var(--sm)",
         "fs-md": "var(--md)",
         "fs-lg": "var(--lg)",
         "fs-xl": "var(--xl)",
         "fs-2xl": "var(--2xl)",
         "fs-3xl": "var(--3xl)",
      },
      fontFamily: {
         "family-primary": ["Satoshi-Variable", "sans-serif"],
         "family-secondary": ['"Roboto"', "sans-serif"],
         "family-tertiary": ["Nuito Sans", "sans-serif"],
      },
      fontWeight: {
         "weight-xl": "700",
         "weight-lg": "600",
         "weight-md": "500",
         "weight-sm": "400",
      },
      zIndex: {
         "layer-background": 5,
         "layer-sidebar": 10,
         "layer-header": 15,
         "layer-popup": 30,
         "layer-content": 45,
         "layer-modal": 50,
         "layer-notification": 60,
         "layer-menu": 65,
         "layer-tooltip": 70,
         "layer-dragging": 80,
         "layer-splash": 85,
         "layer-native": 90,
         "layer-window-titlebar": 99,
         "layer-window-titlebar-buttons": 100,
      },
      extends: {
         screens: {
            // "media-min-h-650": { raw: "(min-height: 650px)" },
            // "media-min-h-668": { raw: "(min-height: 668px)" },
            "media-min-w-500": "500px",
            "media-min-w-850": "850px",
            "media-min-w-1150": "1150px",
            "media-min-w-1400": "1400px",
         },
      },
   },
   plugins: [
      plugin(function ({ addBase }) {
         addBase({
            ":root": {
               "--rgb-none": "rgb(0, 0, 0)",
               "--rgb-full": "rgb(255, 255, 255)",

               //base
               "--base-00": "rgb(0, 0, 0)",
               "--base-05": "rgb(14, 14, 14)",
               "--base-10": "rgb(19, 19, 19)",
               "--base-15": "rgb(22, 22, 22)",
               "--base-20": "rgb(25, 25, 25)",
               "--base-25": "rgb(31, 31, 31)",
               "--base-30": "rgb(37, 37, 37)",
               "--base-35": "rgb(51, 51, 51)",
               "--base-40": "rgb(61, 61, 61)",
               "--base-45": "rgb(72, 72, 72)",
               "--base-50": "rgb(82, 82, 82)",
               "--base-60": "rgb(99, 99, 99)",
               "--base-70": "rgb(144, 144, 144)",
               "--base-80": "rgb(153, 153, 153)",
               "--base-90": "rgb(179, 179, 179)",
               "--base-100": "rgb(191, 191, 191)",
               "--base-110": "rgb(204, 204, 204)",
               "--base-120": "rgb(218, 218, 218)",

               "--brand-1000": "hsl(259, 51%, 10%)",
               "--brand-900": "hsl(259, 51%, 15%)",
               "--brand-800": "hsl(259, 51%, 25%)",
               "--brand-700": "hsl(259, 51%, 35%)",
               "--brand-600": "hsl(259, 51%, 45%)",
               "--brand-500": "hsl(259, 51%, 55%)",
               "--brand-400": "hsl(259, 51%, 65%)",

               "--warning-1000": "hsl(33, 100%, 10%)",
               "--warning-900": "hsl(35, 100%, 15%)",
               "--warning-800": "hsl(37, 100%, 27%)",
               "--warning-700": "hsl(38.9, 100%, 39.9%)",
               "--warning-600": "hsl(38.9, 100%, 55%)",
               "--warning-500": "hsl(38.9, 100%, 62%)",
               "--warning-400": "hsl(39, 100%, 72%)",

               "--destructive-1000": "hsl(7, 80%, 10%)",
               "--destructive-900": "hsl(8, 75%, 15%)",
               "--destructive-800": "hsl(8, 70%, 20%)",
               "--destructive-700": "hsl(9, 65%, 30%)",
               "--destructive-600": "hsl(10, 60%, 40%)",
               "--destructive-500": "hsl(10, 60%, 51%)",
               "--destructive-400": "hsl(10, 70%, 60%)",

               "--success-1000": "hsl(141, 20%, 5%)",
               "--success-900": "hsl(141, 25%, 10%)",
               "--success-800": "hsl(141, 30%, 20%)",
               "--success-700": "hsl(141, 35%, 30%)",
               "--success-600": "hsl(141, 40%, 40%)",
               "--success-500": "hsl(141, 45%, 52%)",
               "--success-400": "hsl(141, 50%, 60%)",

               "color-scheme": "dark",
               "--accent-h": "259",
               "--accent-s": "51%",
               "--accent-l": "45%",

               "--color-accent-hsl": "var(--accent-h), var(--accent-s), var(--accent-l)",
               "--color-accent": "hsl(var(--color-accent-hsl))",
               "--color-accent-1":
                  "hsl(calc(var(--accent-h) - 3), calc(var(--accent-s) * 1.05), calc(var(--accent-l) * 1.14))",
               "--color-accent-2":
                  "hsl(calc(var(--accent-h) - 5), calc(var(--accent-s) * 1.1), calc(var(--accent-l) * 1.25))",

               "--interactive-base": "var(--base-25)",
               "--interactive-hover": "var(--base-30)",
               "--interactive-accent": "var(--color-accent-1)",
               "--interactive-accent-hover": "var(--color-accent-2)",

               "--background-primary": "var(--base-00)",
               "--background-primary-alt": "var(--base-10)",
               "--background-secondary": "var(--base-15)",
               "--background-secondary-alt": "var(--base-20)",
               "--background-modifier-primary-form-field": "var(--base-10)",
               "--background-modifier-secondary-form-field": "var(--base-25)",
               "--background-modifier-border": "var(--base-30)",
               "--background-modifier-border-hover": "var(--base-35)",
               "--background-modifier-border-focus": "var(--base-40)",
               "--background-modifier-box-shadow": "rgba(0, 0, 0, 0.254)",
               "--background-modifier-error-hsl": "var(--destructive-500)",
               "--background-modifier-error": "var(--background-modifier-error-hsl)",
               "--background-modifier-error-hover": "var(--destructive-400)", // might change to 500 idk.
               "--background-modifier-success-hsl": "var(--success-500)",
               "--background-modifier-success": "var(--background-modifier-success-hsl)",

               "--text-normal": "var(--base-100)",
               "--text-muted": "var(--base-60)",
               "--text-faint": "var(--base-50)",
               "--text-on-accent": "white",
               "--text-on-accent-inverted": "black",
               "--text-error": "var(--destructive-600)",
               "--text-warning": "var(--warning-600)",
               "--text-success": "var(--success-600)",
               "--text-accent": "var(--color-accent)",
               "--text-accent-hover": "var(--color-accent-hover)",

               "--link-color": "var(--text-accent)",
               "--link-color-hover": "var(--text-accent-hover)",

               "--modal-background": "var(--background-primary)",

               // // borders
               // // darkmode
               // "--border-primary-dark": "var(--base-20)",
               // "--border-secondary-dark": "var(--base-25)",
               // "--border-tertiary-dark": "var(--base-30)",
               // "--border-primary-alt-dark": "var(--base-15)",
               // "--border-secondary-alt-dark": "var(--base-35)",
               // "--border-tertiary-alt-dark": "var(--base-40)",
               // "--border-muted-dark": "var(--base-50)",

               // // lightmode
               // "--border-primary-light": "var(--base-110)",
               // "--border-secondary-light": "var(--base-100)",
               // "--border-tertiary-light": "var(--base-90)",
               // "--border-primary-alt-light": "var(--base-95)",
               // "--border-secondary-alt-light": "var(--base-80)",
               // "--border-tertiary-alt-light": "var(--base-70)",
               // "--border-muted-light": "var(--base-60)",

               // "--text-error-dark": "var(--destructive-700)",
               // "--text-warning-dark": "var(--warning-700)",
               // "--text-info-dark": "var(--base-90)",
               // "--text-link-dark": "var(--brand-500)",
               // "--text-heading-dark": "var(--brand-700)",
               // "--text-placeholder-dark": "var(--base-50)",
               // "--text-disabled-dark": "var(--base-35)",
               // "--text-brand-accent-dark": "var(--brand-600)",

               // fontfamilies
               "--font-primary": '"Satoshi-Variable", sans-serif',
               "--font-secondary": '"Roboto", sans-serif',
               "--font-tertiary": '"Nunito Sans", sans-serif',

               // fontsize
               "--xs": "0.75rem",
               "--sm": "0.875rem",
               "--md": "1rem",
               "--lg": "1.25rem",
               "--xl": "1.5rem",
               "--2xl": "2rem",
               "--3xl": "3rem",
            },
         });
      }),
   ],
};
