/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthorizedImport } from './routes/unauthorized'
import { Route as TestImport } from './routes/test'
import { Route as OnboardingRouteImport } from './routes/_onboarding/route'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as IndexImport } from './routes/index'
import { Route as LegalTosImport } from './routes/legal/tos'
import { Route as LegalPrivacyPolicyImport } from './routes/legal/privacy-policy'
import { Route as OnboardingOnboardingImport } from './routes/_onboarding/onboarding'
import { Route as AppSearchRouteImport } from './routes/_app/_search/route'
import { Route as AppHomeRouteImport } from './routes/_app/_home/route'
import { Route as AppSearchSearchImport } from './routes/_app/_search/search'
import { Route as AppLibrariesLibrariesImport } from './routes/_app/_libraries/libraries'
import { Route as AppHomeHomeImport } from './routes/_app/_home/home'
import { Route as AppLibrariesLibraryRouteImport } from './routes/_app/_libraries/_library/route'
import { Route as AppLibrariesLibraryLibraryIdImport } from './routes/_app/_libraries/_library/$libraryId'

// Create/Update Routes

const UnauthorizedRoute = UnauthorizedImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRouteRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LegalTosRoute = LegalTosImport.update({
  id: '/legal/tos',
  path: '/legal/tos',
  getParentRoute: () => rootRoute,
} as any)

const LegalPrivacyPolicyRoute = LegalPrivacyPolicyImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingOnboardingRoute = OnboardingOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const AppSearchRouteRoute = AppSearchRouteImport.update({
  id: '/_search',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppHomeRouteRoute = AppHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSearchSearchRoute = AppSearchSearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppSearchRouteRoute,
} as any)

const AppLibrariesLibrariesRoute = AppLibrariesLibrariesImport.update({
  id: '/_libraries/libraries',
  path: '/libraries',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppHomeHomeRoute = AppHomeHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppHomeRouteRoute,
} as any)

const AppLibrariesLibraryRouteRoute = AppLibrariesLibraryRouteImport.update({
  id: '/_libraries/_library',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppLibrariesLibraryLibraryIdRoute =
  AppLibrariesLibraryLibraryIdImport.update({
    id: '/$libraryId',
    path: '/$libraryId',
    getParentRoute: () => AppLibrariesLibraryRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedImport
      parentRoute: typeof rootRoute
    }
    '/_app/_home': {
      id: '/_app/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/_search': {
      id: '/_app/_search'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_onboarding/onboarding': {
      id: '/_onboarding/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/legal/tos': {
      id: '/legal/tos'
      path: '/legal/tos'
      fullPath: '/legal/tos'
      preLoaderRoute: typeof LegalTosImport
      parentRoute: typeof rootRoute
    }
    '/_app/_libraries/_library': {
      id: '/_app/_libraries/_library'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLibrariesLibraryRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/_home/home': {
      id: '/_app/_home/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeHomeImport
      parentRoute: typeof AppHomeRouteImport
    }
    '/_app/_libraries/libraries': {
      id: '/_app/_libraries/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof AppLibrariesLibrariesImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/_search/search': {
      id: '/_app/_search/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchSearchImport
      parentRoute: typeof AppSearchRouteImport
    }
    '/_app/_libraries/_library/$libraryId': {
      id: '/_app/_libraries/_library/$libraryId'
      path: '/$libraryId'
      fullPath: '/$libraryId'
      preLoaderRoute: typeof AppLibrariesLibraryLibraryIdImport
      parentRoute: typeof AppLibrariesLibraryRouteImport
    }
  }
}

// Create and export the route tree

interface AppHomeRouteRouteChildren {
  AppHomeHomeRoute: typeof AppHomeHomeRoute
}

const AppHomeRouteRouteChildren: AppHomeRouteRouteChildren = {
  AppHomeHomeRoute: AppHomeHomeRoute,
}

const AppHomeRouteRouteWithChildren = AppHomeRouteRoute._addFileChildren(
  AppHomeRouteRouteChildren,
)

interface AppSearchRouteRouteChildren {
  AppSearchSearchRoute: typeof AppSearchSearchRoute
}

const AppSearchRouteRouteChildren: AppSearchRouteRouteChildren = {
  AppSearchSearchRoute: AppSearchSearchRoute,
}

const AppSearchRouteRouteWithChildren = AppSearchRouteRoute._addFileChildren(
  AppSearchRouteRouteChildren,
)

interface AppLibrariesLibraryRouteRouteChildren {
  AppLibrariesLibraryLibraryIdRoute: typeof AppLibrariesLibraryLibraryIdRoute
}

const AppLibrariesLibraryRouteRouteChildren: AppLibrariesLibraryRouteRouteChildren =
  {
    AppLibrariesLibraryLibraryIdRoute: AppLibrariesLibraryLibraryIdRoute,
  }

const AppLibrariesLibraryRouteRouteWithChildren =
  AppLibrariesLibraryRouteRoute._addFileChildren(
    AppLibrariesLibraryRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppHomeRouteRoute: typeof AppHomeRouteRouteWithChildren
  AppSearchRouteRoute: typeof AppSearchRouteRouteWithChildren
  AppLibrariesLibraryRouteRoute: typeof AppLibrariesLibraryRouteRouteWithChildren
  AppLibrariesLibrariesRoute: typeof AppLibrariesLibrariesRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHomeRouteRoute: AppHomeRouteRouteWithChildren,
  AppSearchRouteRoute: AppSearchRouteRouteWithChildren,
  AppLibrariesLibraryRouteRoute: AppLibrariesLibraryRouteRouteWithChildren,
  AppLibrariesLibrariesRoute: AppLibrariesLibrariesRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppLibrariesLibraryRouteRouteWithChildren
  '/test': typeof TestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/tos': typeof LegalTosRoute
  '/home': typeof AppHomeHomeRoute
  '/libraries': typeof AppLibrariesLibrariesRoute
  '/search': typeof AppSearchSearchRoute
  '/$libraryId': typeof AppLibrariesLibraryLibraryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppLibrariesLibraryRouteRouteWithChildren
  '/test': typeof TestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/onboarding': typeof OnboardingOnboardingRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/tos': typeof LegalTosRoute
  '/home': typeof AppHomeHomeRoute
  '/libraries': typeof AppLibrariesLibrariesRoute
  '/search': typeof AppSearchSearchRoute
  '/$libraryId': typeof AppLibrariesLibraryLibraryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_onboarding': typeof OnboardingRouteRouteWithChildren
  '/test': typeof TestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/_home': typeof AppHomeRouteRouteWithChildren
  '/_app/_search': typeof AppSearchRouteRouteWithChildren
  '/_onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/tos': typeof LegalTosRoute
  '/_app/_libraries/_library': typeof AppLibrariesLibraryRouteRouteWithChildren
  '/_app/_home/home': typeof AppHomeHomeRoute
  '/_app/_libraries/libraries': typeof AppLibrariesLibrariesRoute
  '/_app/_search/search': typeof AppSearchSearchRoute
  '/_app/_libraries/_library/$libraryId': typeof AppLibrariesLibraryLibraryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/test'
    | '/unauthorized'
    | '/onboarding'
    | '/legal/privacy-policy'
    | '/legal/tos'
    | '/home'
    | '/libraries'
    | '/search'
    | '/$libraryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/test'
    | '/unauthorized'
    | '/onboarding'
    | '/legal/privacy-policy'
    | '/legal/tos'
    | '/home'
    | '/libraries'
    | '/search'
    | '/$libraryId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_onboarding'
    | '/test'
    | '/unauthorized'
    | '/_app/_home'
    | '/_app/_search'
    | '/_onboarding/onboarding'
    | '/legal/privacy-policy'
    | '/legal/tos'
    | '/_app/_libraries/_library'
    | '/_app/_home/home'
    | '/_app/_libraries/libraries'
    | '/_app/_search/search'
    | '/_app/_libraries/_library/$libraryId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  TestRoute: typeof TestRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTosRoute: typeof LegalTosRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  TestRoute: TestRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTosRoute: LegalTosRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_onboarding",
        "/test",
        "/unauthorized",
        "/legal/privacy-policy",
        "/legal/tos"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/_home",
        "/_app/_search",
        "/_app/_libraries/_library",
        "/_app/_libraries/libraries"
      ]
    },
    "/_onboarding": {
      "filePath": "_onboarding/route.tsx",
      "children": [
        "/_onboarding/onboarding"
      ]
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/unauthorized": {
      "filePath": "unauthorized.tsx"
    },
    "/_app/_home": {
      "filePath": "_app/_home/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_home/home"
      ]
    },
    "/_app/_search": {
      "filePath": "_app/_search/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_search/search"
      ]
    },
    "/_onboarding/onboarding": {
      "filePath": "_onboarding/onboarding.tsx",
      "parent": "/_onboarding"
    },
    "/legal/privacy-policy": {
      "filePath": "legal/privacy-policy.tsx"
    },
    "/legal/tos": {
      "filePath": "legal/tos.tsx"
    },
    "/_app/_libraries/_library": {
      "filePath": "_app/_libraries/_library/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_libraries/_library/$libraryId"
      ]
    },
    "/_app/_home/home": {
      "filePath": "_app/_home/home.tsx",
      "parent": "/_app/_home"
    },
    "/_app/_libraries/libraries": {
      "filePath": "_app/_libraries/libraries.tsx",
      "parent": "/_app"
    },
    "/_app/_search/search": {
      "filePath": "_app/_search/search.tsx",
      "parent": "/_app/_search"
    },
    "/_app/_libraries/_library/$libraryId": {
      "filePath": "_app/_libraries/_library/$libraryId.tsx",
      "parent": "/_app/_libraries/_library"
    }
  }
}
ROUTE_MANIFEST_END */
